common: &common

  pool: 30
  host: 127.0.0.1
  adapter: postgresql
  encondeing: unique
  reconnect: false

default:
  <<: *common
  database: <%= Rails.application.credentials.default_database %>
  username: <%= Rails.application.credentials.default_username %>
  password: <%= Rails.application.credentials.default_password %>
  port: 5432

development:
  <<: *common
  database: <%= Rails.application.credentials.dev_database %>
  username: <%= Rails.application.credentials.dev_username %>
  password: <%= Rails.application.credentials.dev_password %>
  port: 5432
  
test:
  <<: *common
  database: <%= Rails.application.credentials.test_database %>
  username: <%= Rails.application.credentials.test_username %>
  password: <%= Rails.application.credentials.test_password %>
  
  port: 5432

production:
  <<: *common
  database: <%= Rails.application.credentials.production_database %>
  username: <%= Rails.application.credentials.production_username %>
  password: <%= Rails.application.credentials.production_password %>
  port: 5432
  
  
  