common: &common
  pool: 30
  host: 127.0.0.1
  adapter: postgresql
  encondeing: unique
  reconnect: false

default:
  <<: *common
  database: "quiniela"
  username: "admin_quiniela"
  password: "123456"
  port: 5432

development:
  <<: *common
  database: "quiniela_dev"
  username: "admin_quiniela"
  password: "123456"
  port: 5432
  
test:
  <<: *commo
  database: "quiniela_test"
  username: "admin_quiniela"
  password: "123456"
  port: 5432


production:
  <<: *common
  database: "quiniela_production"
  username: "admin_quiniela"
  password: "123456"
  port: 5432
  
  
  